name: Semantic Release

on:
  push:
    branches: [main]

jobs:
  tag_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.getversion.outputs.version }}
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: pip install python-semantic-release==7.34.6
    - name: Get version
      id: getversion
      run: |
        release_version=$(semantic-release print-version 2>/dev/null)
        echo "version=$release_version" >> $GITHUB_OUTPUT
    - name: Set Github creds
      uses: fregante/setup-git-user@v2
    - name: Tag release
      run: semantic-release publish
